### ISSUE TITLE
edata_cname is non unique

### ISSUE THREAD

**Issue by imariwalker** [lmbramer/fticRanalysis#18]
peak_data = as.peakData(e_data = edata, f_data = fdata, e_meta = emeta, edata_cname = "Mass", fdata_cname = "SampleID",
+                          mass_cname = "Mass", c_cname = "C", h_cname = "H", o_cname = "O", n_cname = "N", s_cname = "S", p_cname = "P", isotopic_cname = "C13", isotopic_notation = "1")
Error in .as.peakData(e_data, f_data, e_meta, edata_cname, fdata_cname,  : 
  The 'edata_cname' identifier is non-unique.

**Comment by imariwalker** [comment]
Sorry that looked weird. See here: 

peak_data = as.peakData(e_data = edata, f_data = fdata, e_meta = emeta, edata_cname = "Mass", fdata_cname = "SampleID",   mass_cname = "Mass", c_cname = "C", h_cname = "H", o_cname = "O", n_cname = "N", s_cname = "S", p_cname = "P",  isotopic_cname = "C13", isotopic_notation = "1")


Error in .as.peakData(e_data, f_data, e_meta, edata_cname, fdata_cname,  : 
  The 'edata_cname' identifier is non-unique.

When I change the name to be something different I get: Peak/Mass column Mass not found in e_meta. Column names for peak/mass identifiers must match for e_data and e_meta. See details of as.peakData for specifying column names.

**Comment by clabornd** [comment]
Hello sorry responding to this a year later, the regular maintainers have all been quite busy.  Please check that the original column name you supplied has unique values, i.e.:

```
length(unique(edata[,"Mass"])) == length(edata[,"Mass"])
```
