### ISSUE TITLE
Not compatible with new versions of R

### ISSUE THREAD

**Issue by maggiebowman** [lmbramer/fticRanalysis#23]
Warning in install.packages :
  package ‘ftmsRanalysis’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by clabornd** [comment]
This package is not published on CRAN, please use `devtools::install_github("EMSL-Computing/ftmsRanalysis")`
