### ISSUE TITLE
Uniqueness VanKrevlan

### ISSUE THREAD

**Issue by ematula3** [lmbramer/fticRanalysis#28]
I can't find any way to customize the final graph in https://emsl-computing.github.io/ftmsRanalysis/articles/ftmsRanalysis.html. 
Observed in both is sometimes not useful to see and the compound classes get in the way.

**Comment by clabornd** [comment]
Hello, to remove the compound classes boxes, pass `showVKBounds = FALSE`:

```
vanKrevelenPlot(crop_unique, colorCName = "uniqueness_gtest", showVKBounds = FALSE)
```

For hiding the 'observed in both', you can either click the legend entry in the interactive plotly plot to hide those points, or if you need the points and legend removed, you can try storing and then editing the plot object using `plotly::style`:

```
p <- vanKrevelenPlot(crop_unique, colorCName = "uniqueness_gtest", showVKBounds = FALSE)

# in the plot p, set visible = FALSE for the third trace
# which happens to be the points for 'observed in both'
plotly::style(p, visible = FALSE, traces = c(3))
```

which seems to work (plotly 4.10.2)

![newplot (2)](https://github.com/EMSL-Computing/ftmsRanalysis/assets/31082141/16465ffe-4383-4e29-8dcd-df93279e41f4)

**Comment by ematula3** [comment]
Neat, that works great. What about making colors standard? For this same
graph Unique to x and Unique to y swap sometimes when I'm graphing
different subsets of data.

**Comment by clabornd** [comment]
I believe that is due to the order in which the different levels appear in `crop_unique$e_data$uniqueness_gtest`, which may change for different subsets of data.  

You can specify custom colors/color order using the `colorPal` argument to `vanKrevelenPlot`:

```
color_levels = unique(na.omit(crop_unique$e_data$uniqueness_gtest))
my_colors = c('red', 'green', 'blue')
# color_levels[1] will have color my_colors[1]

# create a palette using scales
mypal <- scales::col_factor(my_colors, levels = color_levels)

p <- vanKrevelenPlot(
  crop_unique, 
  colorCName = "uniqueness_gtest", 
  showVKBounds = FALSE, 
  colorPal = mypal
)

plotly::style(p, visible = FALSE, traces = c(3))
``` 



Make sure the ordering is aligned in `color_levels` and `my_colors`

**Comment by ematula3** [comment]
Thanks! I also found that releveling the factors works really well too:
july_unique$e_data$uniqueness_gtest <-
relevel(as.factor(july_unique$e_data$uniqueness_gtest), ref='Unique to
control')

**Comment by clabornd** [comment]
np, glad you found a clean solution.
