### ISSUE TITLE
uniqueness_gtest results don't make sense

### ISSUE THREAD

**Issue by allison-thompson** [lmbramer/fticRanalysis#5]
I'm trying to run the uniqueness_gtest function in order to plot a van Krevelen diagram showing compounds unique to each group. I have 3 replicates in each group. Even expanding the significance threshold to 0.15, I'm not getting anything as significant, across nearly 20 comparisons. I've gone through and looked and there are some instances where I have 3 replicates seen in one group and only 1 in the other - seems like this should pop out? Looking at NOSC comparisons, there are obvious differences, so it's weird that nothing is showing up in the van Krevelen.

**Comment by lmbramer** [comment]
3 present vs 1 present with replicates in each group yields a p-value of ~0.38
