### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by biogeoc** [lmbramer/fticRanalysis#7]
package ‘glue’ successfully unpacked and MD5 sums checked

Error: Failed to install 'ftmsRanalysis' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘glue’

Any suggestions?  Thanks!

**Comment by lmbramer** [comment]
@biogeoc - can you provide details of your install. Are you installing via devtools::install_github()? Can you send your sessionInfo(), please?
