### ISSUE TITLE
error running the vignette ftmsRanalysis.Rmd 

### ISSUE THREAD

**Issue by jeffreyblanchard** [lmbramer/fticRanalysis#9]
In running the vignette ftmsRanalysis.Rmd 
I got the following error at line 301
```{r}
byGroup <- divideByGroupComparisons(peakObj, 
                                comparisons = "all")[[1]]$value

Loading required package: datadr
there is no package called ‘datadr’Error in kvPair(key, val) : could not find function "kvPair"

However, when I search for datadr
https://cran.r-project.org/web/packages/datadr/index.html
Package ‘datadr’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2020-01-02 as nothing now depends on it.
The most recent check results can be obtained from the check results archive.
However even in the archive the package is not available.
If I try to just knit the whole file I get hung at the same point with the attached error
![ftmsRanalysis](https://user-images.githubusercontent.com/4509174/97483485-da341080-192d-11eb-8de6-58e729238025.png)

**Comment by jeffreyblanchard** [comment]
We also run into the same issue running mapping_to_metacyc.Rmd on a different computer and installation of R at
rxnGroupCompData <- divideByGroupComparisons(rxnData2, comparisons="all")
line 98

**Comment by jeffreyblanchard** [comment]
Found datadr in delta-rho - https://github.com/delta-rho/datadr
When installed using devtools
devtools::install_github("delta-rho/datadr")
Now both vignettes work beautifully.
Thanks for putting this package together!

**Comment by lmbramer** [comment]
@jeffreyblanchard - Glad you found a solution and thanks for posting. We will be switching over to tidyverse syntax, on the backend, so this won't be an issue for the next release!
